apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name}}-configmap
  labels:
    label1: {{.Chart.Name}}
data:
  # When the config map is mounted as a volume, these will be created as files.
  app.values: value=Value configMap1