apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Chart.Name}}
  name: {{.Chart.Name}}-service
spec:
  ports:
    - name: {{.Chart.Name}}
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{.Chart.Name}}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
